#week03 / wine

컴퓨터공학과 / 202433638 / 장영환

In [ ]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

path = '/content/drive/MyDrive/Colab Notebooks/인공지능개론/week03/wine.csv'
df = pd.read_csv(path)

#forClassification
y=df['Wine']
x=df.drop('Wine',axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.25,random_state=0)

#Logistic Regression Classifier

In [ ]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(x_train, y_train)
pred_lr = clf_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#DecisionTree Classifier

In [ ]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]


#RandomForest Classifier

In [ ]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)

pred = rf_clf.predict(x_test)

print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

0.9777777777777777
[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]


#KNN Classifier

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5) #tie 방지를 위해 홀수값으로
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)
from sklearn import metrics

scores = metrics.accuracy_score(y_test, y_pred)
print(scores)

0.7333333333333333
