#week13 / SPAM



컴퓨터공학과 / 202433638 / 장영환

짧은 문장을 입력으로 받아서 스팸성 문장인지 아닌지 이진 분류(binary classification) 하는 아주 작은 NLP 실습 예제

핵심은 컴퓨터는 문자열을 직접 이해하지 못하므로, 텍스트를 숫자로 바꾸고, 그 숫자를 다시 의미를 담은 벡터로 학습한다는 점

In [7]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [8]:
docs = [ 'additional income',
'best price',
'big bucks',
'cash bonus',
'earn extra cash',
'spring savings certificate',
'valero gas marketing',
'all domestic employees',
'nominations for oct',
'confirmation from spinner']
labeIs = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

각 문장은 1 또는 0이라는 라벨을 가진다.

문장을 보고 1인지 0인지 예측하는 모델을 만든다

In [9]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[22, 8], [24, 29], [30, 39], [10, 18], [32, 45, 10], [28, 24, 37], [12, 31, 1], [2, 38, 41], [32, 2, 15], [29, 11, 38]]


각 문장을 단어 단위로 나누고, 각 단어를 1~49 범위의 정수로 바꾼다

In [10]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen = max_length, padding='post')
print(padded_docs)

[[22  8  0  0]
 [24 29  0  0]
 [30 39  0  0]
 [10 18  0  0]
 [32 45 10  0]
 [28 24 37  0]
 [12 31  1  0]
 [ 2 38 41  0]
 [32  2 15  0]
 [29 11 38  0]]


신경망은 입력 크기가 일정해야 하므로 모든 문장을 길이 4로 맞춘다

In [12]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation= 'sigmoid'))
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


단어 번호 1개 → 8차원 벡터 1개

문장 길이 4 → 4개의 단어 벡터

최종 출력 → 4 × 8

In [14]:
model.fit(padded_docs, labeIs, epochs=50, verbose=0)
loss, accuracy = model.evaluate(padded_docs,labeIs, verbose=0)
print('정확도=', accuracy)

정확도= 1.0


학습에 사용한 같은 데이터로 다시 평가

In [15]:
test_doc = ['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding = 'post')
print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
[[0.58523333]]
