#week02 / breast cancer

컴퓨터공학과 / 202433638 / 장영환

In [ ]:
import pandas as pd
import numpy as np
path = '/content/drive/MyDrive/Colab Notebooks/인공지능개론/week02/breast_cancer (1).csv'
df = pd.read_csv(path)

In [ ]:
y=df['label']
y.value_counts()
X=df.drop('label',axis=1)
#axis는 어느 축을 기준으로  1은 열(column) 기준, 0은 행(row) 기준
# y는 정답 값, x는 입력 특성

#Logistic Regression

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)
# x, y는 위치인자, test_size=0.25, random_state=0 → 키워드 인자(keyword arguments)이름을 지정해서 전달함
# 이떄 train_test_split()은 4개의 값을 반환
# 데이터를 학습용 75%, 테스트용 25%로 나눈다.
# random_state=0은 같은 분할을 재현하기 위한 설정이다. 즉 랜덤결과 고정

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)
pred_lr = clf_lr.predict(X_test)
# 로지스틱 회귀 모델을 학습
# 테스트 데이터에 대해 예측 수행

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

# accuracy_score: 전체 정확도
# confusion_matrix: 어떤 클래스를 얼마나 맞추고 틀렸는지 보여줌

#결과

# 정확도: 0.9720
# 실제 0인 것 중 52개 맞추고 1개 틀림
# 실제 1인 것 중 87개 맞추고 3개 틀림


--- Logistic Regression Classifier ---
0.972027972027972
[[52  1]
 [ 3 87]]


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#Decision Tree

트리는 본질적으로 if-else 규칙들의 집합이다.

분류용 결정트리에서 트리는 각 노드에서
“어떤 기준으로 나누면 클래스가 가장 잘 구분될까?”를 찾는다.

단점

과적합(overfitting) 이 잘 된다

데이터가 조금만 바뀌어도 구조가 크게 달라질 수 있다

일반화 성능이 불안정할 수 있다

In [ ]:
from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0) #결정트리 모델 생성
clf_dt.fit(X_train, y_train) #학습

pred_dt = clf_dt.predict(X_test) #예측

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

#결과
# accuracy_score: 전체 중 맞춘 비율
# [[실제 0을 0으로 예측, 실제 0을 1로 예측],
#  [실제 1을 0으로 예측, 실제 1을 1로 예측]]


--- Decision Tree Classifier ---
0.8951048951048951
[[49  4]
 [11 79]]


#RandomForest

결정트리를 여러 개 만든 뒤 합치는 앙상블(ensemble) 모델

분류일 때 / 여러트리가 예측한 클래스를 다수결 투표

In [ ]:
from sklearn.ensemble import RandomForestClassifier

print ("\n--- Radom Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)

pred = rf_clf.predict(X_test)
# 테스트 샘플 하나에 대해 여러 트리가 각각 예측한다.
# 분류 문제에서는 최종적으로 다수결 투표(majority voting) 를 한다.

print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))


--- Radom Forest ---
0.9790209790209791
[[52  1]
 [ 2 88]]


#LinearRegression

In [ ]:
df2 = df.drop('label',axis=1)
# label을 없애고, 대신 worst compactness를 정답값(y) 으로
y=df2['worst compactness']
X=df2.drop('worst compactness',axis=1)

In [ ]:
from sklearn.model_selection import train_test_split #데이터 분할
from sklearn.linear_model import LinearRegression #선형회귀 모델
from sklearn.metrics import mean_squared_error #평균제곱오차 계산 함수

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)
model = LinearRegression()  #모델 설정
model.fit(X_train, y_train) #학습
ly_preds = model.predict(X_test) #예측 값

#실제값과 예측값의 차이를 제곱해서 평균낸 값을 출력한다.

# 1. scikit-learn 함수
# 2. NumPy 직접 구현
# 3. 순수 파이썬 직접 구현

print('평균제곱오차', mean_squared_error(ly_preds, y_test))

# def mse_np(actual, predicted):
#     return np.mean((np.array(actual) - np.array(predicted)) ** 2)
# print('평균제곱오차', mse_np(ly_preds, y_test))

# def mse(actual, predicted):
#     sum_square_error = sum((a - p) ** 2for a, p in zip(actual, predicted))
#     mean_square_error = sum_square_error / len(actual)
#     return mean_square_error
# print('평균제곱오차', mse(ly_preds, y_test))

평균제곱오차 0.0004937274846573661
