#week02 / diabetes

컴퓨터공학과 / 202433638 / 장영환

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LinearRegression

path = '/content/drive/MyDrive/Colab Notebooks/인공지능개론/week02/diabetes.csv'

df = pd.read_csv(path)

y=df['Outcome']
y.value_counts()
X=df.drop('Outcome',axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

#Logistic Regression

In [ ]:
clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)
pred_lr = clf_lr.predict(X_test)

print (accuracy_score(y_test, pred_lr))
print("")
print (confusion_matrix(y_test, pred_lr))

0.796875

[[116  14]
 [ 25  37]]


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#Decision Tree

In [ ]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)
pred_dt = clf_dt.predict(X_test)

print (accuracy_score(y_test, pred_dt))
print("")
print (confusion_matrix(y_test, pred_dt))

0.71875

[[102  28]
 [ 26  36]]


#RandomForest

In [ ]:
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)

print(accuracy_score(y_test,pred))
print("")
print (confusion_matrix(y_test, pred))

0.7708333333333334

[[116  14]
 [ 30  32]]


#LinearRegression

In [ ]:
df2=df.drop('Outcome',axis=1)
y=df2['BMI']
X=df2.drop('BMI',axis=1)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)
model = LinearRegression()
model.fit(X_train, y_train)
ly_preds = model.predict(X_test)

print('평균제곱오차', mean_squared_error(ly_preds, y_test))

평균제곱오차 52.23558099742443
